### ISSUE TITLE
Rename connector modules and (optionally) move all connectors to one module

### ISSUE THREAD

**Issue by DonDebonair** [datadudes/sisyphus#1]
According to [Python naming conventions](https://www.python.org/dev/peps/pep-0008/#package-and-module-names), modules (and hence the file names) should be all lowercase and optionally underscores. That means that [BaseConnector.py](https://github.com/datadudes/sisyphus/blob/master/sisyphus/connectors/BaseConnector.py), [MySqlConnector.py](https://github.com/datadudes/sisyphus/blob/master/sisyphus/connectors/MySqlConnector.py) and [PostgreSqlConnector.py](https://github.com/datadudes/sisyphus/blob/master/sisyphus/connectors/PostgreSqlConnector.py) should probably be renamed to something like `base_connector.py`, `mysql_connector.py` and `postgresql_connector.py`.

In Python it is also quite normal though, to have multiple related classes in 1 module, especially if the classes are quite small (which is the case here). So I would consider moving all 3 connector classes into 1 module `connectors.py`, and thereby get rid of the package all together. But that is optional of course ;)

**Comment by mkrcah** [comment]
Good point, files renamed. I kept the classes in separate files for now, so the import statements can be nicely on top of the file instead of within the connector methods.
