### ISSUE TITLE
Consider having db drivers as optional requirements

### ISSUE THREAD

**Issue by DonDebonair** [datadudes/sisyphus#2]
Instead of having `psycopg2` and `mysql-connector-python` in the `requirements.txt` file, you could have something like this in the `setup.py`:

``` python
extras_require={
    'mysql': ["mysql-connector-python==2.0.3"],
    'psql': ["psycopg2==2.6"],
},
```

This allows people to install only what they need by using the following commands:

``` bash
$ pip install sisyphus # no db drivers
$ pip install sisyphus[mysql] # only mysql driver
$ pip install sisyphus[mysql,psql] # both mysql and postgres drivers
```

etc.

**Comment by mkrcah** [comment]
Good idea, especially if there will be more connectors available. Updated setup.py, closing the issue.
